import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // Admin Modules

  {
    path: '/mnf/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },     
  {
    path: '',
    title: `Manufacture's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/profile',
        title: 'View/Edit Profile',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/customise_profile',
        title: 'Customize Profile for Customers',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }
     
    ],
  },
  {
    path: '/mnf/brand',
    title: `Brand`,
    iconType: 'material-icons-outlined',
    icon: 'business',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },    
  {
    path: '/mnf/category',
    title: `Add Discounts/Schemes`,
    iconType: 'material-icons-outlined',
    icon: 'view_timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },    
  {
    path: '',
    title: `Distributor's Management`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/new-distributor',
        title: 'Invite New Distributor',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/manage-distributor',
        title: 'View & Manage Distributors',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/bulk-upload',
        title: 'Bulk Invite',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/invite-status',
        title: 'Invite Status',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/add-new-product',
        title: 'Add New Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['manufacture'],
        submenu: [],
      },
      {
        path: '/mnf/manage-product',
        title: 'View And Manage Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      // {
      //   path: '/mnf/stock-inventory',
      //   title: 'Stock Inventory',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },

  // for request
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/wholselers-Requests',
        title: "Wholesaler Request List",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/Rejected-Requests',
        title: "Rejected Request List",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },

  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/wls-list',
        title: 'New Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/wls-list',
        title: 'Pending Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View Order Status',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Returns  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/return-mng/order-return',
        title: 'Order Return',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Other Services`,
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'Logistics partners',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Product Photo And Video Shoot',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/common/user-category',
        title: 'Setting',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },

  // -------------------------------------- retailer -------------------------------------//
  {
    path: '/retailer/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  }, 
  {
    path: '/retailer/retailer-profile',
    title: `Retailer's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  },  
  // {
  //   path: '',
  //   title: `Retailer's Management`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'group_add',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/retailer/new-retailer',
  //       title: 'Invite New Retailer',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/manage-retailer',
  //       title: 'View And Manage Retailer',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/bulk-upload',
  //       title: 'Bulk Invite',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/invite-status',
  //       title: 'Invite Status',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      {
        path: '/retailer/new/wholseller-list3',
        title: "Wholesaler List",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/new/cart-product2-retailer',
        title: "Cart Products",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View And Manage Product',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  // for request
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      {
        path: '/retailer/request-to-wholesaler',
        title: 'Request To Wholesaler',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/requested-wholesaler-list',
        title: 'Requested Wholesaler List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'New Orders',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View Order Status',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/retailer/new/view-retailerpo',
        title: 'Retailer PO',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
     
    ],
  },
  // {
  //   path: '',
  //   title: `Returns  Management`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'widgets',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/users/trainer',
  //       title: 'Order Return',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/users/skill-trainer',
  //       title: 'Order Cancelled',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },      
  //   ],
  // },
  // {
  //   path: '',
  //   title: `Other Services`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'supervised_user_circle',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/users/trainer',
  //       title: 'Logistics partners',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/users/skill-trainer',
  //       title: 'Product Photo And Video Shoot',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },      
  //   ],
  // },
  // -------------------------------------- wholesaler -------------------------------------//
  {
    path: '/wholesaler/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  }, 
  {
    path: '/wholesaler/profile',
    title: `Wholesaler's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  },  
  {
    path: '/wholesaler/associated-mnf-list',
    title: `Associated Manufacturer-List`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  },  
  {
    path: '',
    title: `Retailer's Management`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/new-retailer',
        title: 'Invite New Retailer',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/manage-retailer',
        title: 'View And Manage Retailers',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/bulk-upload',
        title: 'Bulk Invite',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/invite-status',
        title: 'Invite Status',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/request-to-mnf',
        title: 'Request To Manufacturer',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/requested-mnf_list',
        title: 'Requested Manufacturer List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/retailers-requests-list',
        title: "Request's From Retailers",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },    
      {
        path: '/wholesaler/rejected-retailsers-list',
        title: 'Rejected Retailer List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/product/mnf-list',
        title: `Manufacturer's Products`,
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/product/ordered-products',
        title: `Products`,
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/product/wishlist-product',
        title: 'Wishlist',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      {
        path: '/wholesaler/product/add-to-cart',
        title: 'Cart Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },
  // for request
  
  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/order-mng/mnf-list-challan',
        title: 'New Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/order-mng/place-order',
        title: 'PO List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      // {
      //   path: '/wholesaler/order-mng/ordered-products',
      //   title: 'Ordered Products',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // }, 
      {
        path: '/wholesaler/order-mng/RelatorPo',
        title: 'Retailer Po',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }, 
     
           
    ],
  },
  {
    path: '',
    title: `Returns  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/return-mng/return-product',
        title: 'Order Return',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Other Services`,
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'Logistics partners',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Product Photo And Video Shoot',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/common/user-category',
        title: 'Setting',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }, 
    ],
  },
  // {
  //   path: '',
  //   title: 'User Management',
  //   iconType: 'material-icons-outlined',
  //   icon: 'group_add',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['cluster'],
  //   submenu: [
  //     {
  //       path: '/users/trainer',
  //       title: 'Career Counsellor',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/users/skill-trainer',
  //       title: 'Life Skill Trainer',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

  // ----------------------- Student Modules ---------------------

 
 
  
];
export const ROUTES2: RouteInfo[] = [
  // Admin Modules

  {
    path: '/mnf/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },     
  {
    path: '',
    title: `Manufacture's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/profile',
        title: 'View/Edit Profile',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/customise_profile',
        title: 'Customize Profile for Customers',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }
     
    ],
  },
  {
    path: '/mnf/brand',
    title: `Brand`,
    iconType: 'material-icons-outlined',
    icon: 'business',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },    
  {
    path: '/mnf/category',
    title: `Add Discounts/Schemes`,
    iconType: 'material-icons-outlined',
    icon: 'view_timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: []
  },    
  {
    path: '',
    title: `Distributor's Management`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/new-distributor',
        title: 'Invite New Distributor',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/manage-distributor',
        title: 'View & Manage Distributors',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/bulk-upload',
        title: 'Bulk Invite',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/invite-status',
        title: 'Invite Status',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/new/add-product2',
        title: 'Add New Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['manufacture'],
        submenu: [],
      },
      {
        path: '/mnf/new/manage-product2',
        title: 'View And Manage Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      // {
      //   path: '/mnf/stock-inventory',
      //   title: 'Stock Inventory',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },

  // for request
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/wholselers-Requests',
        title: "Wholesaler Request List",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/Rejected-Requests',
        title: "Rejected Request List",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },

  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/wls-po-list',
        title: 'Wholesaler po list',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/wls-list',
        title: 'New Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/wls-pen-list',
        title: 'Pending Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/mnf/new/mfg-proforma-invoice-list',
        title: 'Proforma Invoice',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View Order Status',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },

  {
    path: '',
    title: `Returns  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      {
        path: '/mnf/new/Return-products',
        title: 'Order Return',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/mnf/return-mng/order-return',  ppp
      //   title: 'Order Return',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Other Services`,
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['manufacture'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'Logistics partners',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Product Photo And Video Shoot',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/common/user-category',
        title: 'Setting',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }, 
    ],
  },

  // -------------------------------------- retailer -------------------------------------//
  {
    path: '/retailer/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  }, 
  {
    path: '/retailer/retailer-profile',
    title: `Retailer's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  },  
  {
    path: '/retailer/retailer-mnf-associated-list',
    title: `Associated Manufacturer List`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  },  {
    path: '/retailer/retailer-whol-associated-list',
    title: `Associated Wholesaler List`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: []
  },  
  // {
  //   path: '',
  //   title: `Retailer's Management`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'group_add',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/retailer/new-retailer',
  //       title: 'Invite New Retailer',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/manage-retailer',
  //       title: 'View And Manage Retailer',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/bulk-upload',
  //       title: 'Bulk Invite',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/retailer/invite-status',
  //       title: 'Invite Status',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      {
        path: '/retailer/product-list-of-mfg',
        title: "Product List of Manufacturer",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/new/wholseller-list3',
        title: "Product List of Wholesaler",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/new/cart-product2-retailer',
        title: "Wholseller Cart Products",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/new/cart-product2-MAn',
        title: "Manufacture Cart Products",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View And Manage Product',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // }, 
      {
        path: '/retailer/new/wishlist-product2',
        title: 'Wishlist',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },
  // for request
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      {
        path: '/retailer/request-to-wholesaler',
        title: 'Request To Wholesaler',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/requested-wholesaler-list',
        title: 'Requested Wholesaler List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['retailer'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'New Orders',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'View Order Status',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/retailer/new/view-retailerpo',
        title: 'Retailer PO',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/retailer/new/view-ManReq',
        title: 'Retailer Order Request',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  // {
  //   path: '',
  //   title: `Returns  Management`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'widgets',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/users/trainer',
  //       title: 'Order Return',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/users/skill-trainer',
  //       title: 'Order Cancelled',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },      
  //   ],
  // },
  // {
  //   path: '',
  //   title: `Other Services`,
  //   iconType: 'material-icons-outlined',
  //   icon: 'supervised_user_circle',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['retailer'],
  //   submenu: [
  //     {
  //       path: '/users/trainer',
  //       title: 'Logistics partners',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/users/skill-trainer',
  //       title: 'Product Photo And Video Shoot',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },      
  //   ],
  // },
  // -------------------------------------- wholesaler -------------------------------------//
  {
    path: '/wholesaler/dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  }, 
  {
    path: '/wholesaler/profile',
    title: `Wholesaler's Profile`,
    iconType: 'material-icons-outlined',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  },  
  {
    path: '/wholesaler/associated-mnf-list',
    title: `Associated Manufacturer-List`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  },  
  {
    path: '/wholesaler/new/product/wholesaler-discount',
    title: `Retailer's Discount`,
    iconType: 'material-icons-outlined',
    icon: 'view_timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: []
  },   
  {
    path: '',
    title: `Retailer's Management`,
    iconType: 'material-icons-outlined',
    icon: 'group_add',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/new-retailer',
        title: 'Invite New Retailer',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/manage-retailer',
        title: "View And Manage Retailers",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/bulk-upload',
        title: 'Bulk Invite',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/invite-status',
        title: 'Invite Status',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: `Request  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/request-to-mnf',
        title: 'Request To Manufacturer',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/requested-mnf_list',
        title: 'Requested Manufacturer List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/retailers-requests-list',
        title: "Request's of Retailers",
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },    
      {
        path: '/wholesaler/rejected-retailsers-list',
        title: 'Rejected Retailer List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },
  {
    path: '',
    title: `Add Product Price`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/viewproductre',
        title: 'Add Price For Retailers',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },    
    ],
  },
  {
    path: '',
    title: `Product Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/new/product/mnf-list',
        title: `Manufacturer's Products`,
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/wholesaler/new/product/ordered-products',
      //   title: `Products`,
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      {
        path: '/wholesaler/new/product/wish-list',
        title: 'Wishlist',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      {
        path: '/wholesaler/new/product/add-to-cart',
        title: 'Cart Product',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
    ],
  },
  // for request
  
  {
    path: '',
    title: `Order Management`,
    iconType: 'material-icons-outlined',
    icon: 'description',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/order-mng/mnf-list-challan',
        title: 'New Orders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/wholesaler/order-mng/place-order',
        title: 'PO List',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },      
      // {
      //   path: '/wholesaler/order-mng/ordered-products',
      //   title: 'Ordered Products',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // }, 
      {
        path: '/wholesaler/order-mng/RelatorPo',
        title: 'Retailers Po',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },  
      // {
      //   path: '/wholesaler/order-mng/RequestProcess',
      //   title: 'Request Process',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },  
      {
        path: '/wholesaler/order-mng/retailormanpo',
        title: 'Retailer-Manufacturer-Po',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }, 
      {
        path: '/wholesaler/order-mng/MNFDChalan',
        title: 'Manufacturer Delivery Challan',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },  
      {
        path: '/wholesaler/order-mng/okproductlist',
        title: 'Accepted Products',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },  
      {
        path: '/wholesaler/order-mng/Performainvoiceshow',
        title: 'Proforma Invoice',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },  
         
    ],
  },
  {
    path: '',
    title: `Returns  Management`,
    iconType: 'material-icons-outlined',
    icon: 'widgets',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      {
        path: '/wholesaler/return-mng/return-product',
        title: 'Order Return',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Order Cancelled',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
    ],
  },
  {
    path: '',
    title: `Other Services`,
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['wholesaler'],
    submenu: [
      // {
      //   path: '/users/trainer',
      //   title: 'Logistics partners',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
      // {
      //   path: '/users/skill-trainer',
      //   title: 'Product Photo And Video Shoot',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },      
      {
        path: '/common/user-category',
        title: 'Setting',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      }, 
    ],
  },
  {
    path: '/super/Super-dashboard',
    title: `Dashboard`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['superadmin'],
    submenu: []
  }, 
  {
    path: '/super/CDN-Mng',
    title: `CDN Management`,
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['superadmin'],
    submenu: []
  }, 
  
];
